- name: Instalar nginx
  apt:
    name: nginx
    state: present

- name: Copiar configuración de Nginx para el balanceador de carga
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reiniciar Nginx