- name: Descargar WordPress
  ansible.builtin.get_url:
    url: "{{ wordpress_download_url }}"
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Descomprimir WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    mode: '0755'

- name: Copiar archivo de configuracion de WordPress
  template:
    src: ../templates/wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    mode: '0644'

- name: Ajustar permisos de WordPress
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: '0755'
  notify: Reiniciar Apache